[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "axolotl_curve25519"
version = "0.4.1-2"
license = {text = "GPLv3 License"}
authors = [
  {name = "Tarek Galal", email = "tare2.galal@gmail.com"},
]
description = "curve25519 with ed25519 signatures, used by libaxolotl"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["curve*", "screenshots*"]

[tool.setuptools.package-dir]
"" = "."
